#!/bin/bash
# Git filter-branch script to correct AI commit attribution
# Generated by Git Commit Attribution Corrector

echo "=== Correcting AI Commit Attribution ==="
echo "AI Author: anthropic_Claude (copilot/claude-sonnet-4)"
echo "AI Email: admin+copilot.claude-sonnet-4@emblemprojects.com"
echo ""

git filter-branch --env-filter '
if [ $GIT_COMMIT = "6034477e1be136653236dd144fe0dfd5dea95b94" ]; then
    echo "Correcting commit 6034477: AI-assisted (Score: 11)"
    export GIT_AUTHOR_NAME="anthropic_Claude (copilot/claude-sonnet-4)"
    export GIT_AUTHOR_EMAIL="admin+copilot.claude-sonnet-4@emblemprojects.com"
    export GIT_COMMITTER_NAME="anthropic_Claude (copilot/claude-sonnet-4)" 
    export GIT_COMMITTER_EMAIL="admin+copilot.claude-sonnet-4@emblemprojects.com"
fi
' --tag-name-filter cat -- --branches --tags

echo ""
echo "Attribution correction complete!"
echo "WARNING: This has rewritten git history!"
echo "Use 'git push --force' to update remote repository"
