@{
    # Module manifest for DeveloperEnvironmentTools
    # Generated by: AI Assistant
    # Generated on: 2025-01-06
    
    RootModule = 'DeveloperEnvironmentTools.psm1'
    ModuleVersion = '1.0.0'
    
    # Module compatibility
    CompatiblePSEditions = @('Desktop', 'Core')
    PowerShellVersion = '5.1'
    
    # Module identification
    GUID = 'b3f4c8e2-1a2b-4c5d-8e9f-1234567890ab'
    Author = 'romar-j'
    CompanyName = 'emblem-projects-inc'
    Copyright = '(c) 2025 emblem-projects-inc. All rights reserved.'
    
    # Module description
    Description = 'Professional PowerShell module for development environment setup, automation, and git workflow configuration. Provides comprehensive capabilities for automating development environment setup, configuring git workflows, and managing development toolchains across projects and teams.'
    
    # Module requirements
    RequiredModules = @()
    RequiredAssemblies = @()
    
    # Exports
    FunctionsToExport = @(
        'Invoke-DevelopmentEnvironmentSetup',
        'Initialize-GitWorkflowAutomation', 
        'Install-PreCommitHooks',
        'Test-EnvironmentConfiguration',
        'New-EnvironmentProfile',
        'Import-TeamConfiguration',
        'Initialize-MultiProjectEnvironment'
    )
    CmdletsToExport = @()
    VariablesToExport = @()
    AliasesToExport = @()
    
    # Module information
    ModuleList = @()
    FileList = @()
    
    # Private data
    PrivateData = @{
        PSData = @{
            # PowerShell Gallery metadata
            Tags = @('Development', 'Environment', 'Automation', 'Git', 'Workflow', 'DevOps', 'Setup', 'Configuration')
            LicenseUri = 'https://github.com/thisis-romar/developer-environment-tools/blob/main/LICENSE'
            ProjectUri = 'https://github.com/thisis-romar/developer-environment-tools'
            IconUri = ''
            ReleaseNotes = @'
## v1.0.0 - Initial Release

### Features
- Complete development environment setup automation
- Git workflow automation and pre-commit hooks
- Multi-platform support (Windows, macOS, Linux)
- Team configuration standardization
- CI/CD integration capabilities
- Extensible configuration system
- Pre-built profiles for popular tech stacks

### Components
- Environment Setup Engine
- Git Workflow Automation
- Configuration Management
- Quality Gates Integration
- Team Standardization Tools

### Supported Tools
- Node.js, Python, .NET, Java, Go, Rust
- VS Code, Git, Docker, PowerShell Core
- ESLint, Prettier, Jest, pytest, SonarQube
- Windows Subsystem for Linux (WSL)

### Use Cases
- Individual developer productivity
- Team environment standardization
- DevOps automation integration
- New developer onboarding
- Code quality enforcement
'@
            ExternalModuleDependencies = @()
        }
    }
    
    # Help and documentation
    HelpInfoURI = 'https://github.com/thisis-romar/developer-environment-tools/blob/main/docs/'
    
    # Default prefix for commands (if needed)
    # DefaultCommandPrefix = 'DevEnv'
}